# Generated by Django 3.2 on 2022-01-08 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20220108_0720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='icon',
        ),
    ]
