# Generated by Django 3.2 on 2022-01-09 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_course_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='pay',
            field=models.FloatField(default=0.0),
        ),
    ]
