# Generated by Django 3.2 on 2022-01-17 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='company_name',
        ),
        migrations.AddField(
            model_name='organization',
            name='company',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
